version: '3.8'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: banco
      MYSQL_USER: user
      MYSQL_PASSWORD: qwerty
    ports:
      - "3306:3306"
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - services-network

  people:
    image: people:latest
    build:
      context: ./people
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker      
    networks:
      - services-network

  account:
    image: account:latest
    build:
      context: ./account
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker      
    networks:
      - services-network

networks:
  services-network:
    driver: bridge
