# Dockerfile for the 'people' microservice
FROM openjdk:17-jdk-slim

WORKDIR /app

COPY target/people-service.jar people-service.jar

EXPOSE 8081

ENTRYPOINT ["java", "-jar", "/app/people-service.jar"]
