# Dockerfile for the 'account' microservice
FROM openjdk:17-jdk-slim

WORKDIR /app

COPY target/account-service.jar account-service.jar

EXPOSE 8082

ENTRYPOINT ["java", "-jar", "/app/account-service.jar"]
